### ISSUE TITLE
Investigate Ecosystem Display in React Wallet

### ISSUE THREAD

**Issue by fundthmcalculus** [trinsic-id/sdk-examples#127]
Confirm that you can provide the ecosystem access token and have the react wallet switch from the default ecosystem.

**Comment by MichaelEdwardBlack** [comment]
This is what you need to do to switch to your own ecosystem. 

On [this line](https://github.com/trinsic-id/sdk-examples/blob/main/browser/react-wallet/src/actions/index.ts#:~:text=const%20serviceOptions%20%3D%20ServiceOptions.fromPartial(%7BserverEndpoint%3A%20%22dev%2Dinternal.trinsic.cloud%22%7D)%3B) you'll need to add your access token

```js
const serviceOptions = ServiceOptions.fromPartial({
    serverEndpoint: "dev-internal.trinsic.cloud",
    authToken: "<YOUR AUTH TOKEN HERE>"
});
```

From my understanding, this should change the service to use your ecosystem associated with that token
