### ISSUE TITLE
React wallet sample getting unresponsive and not working.

### ISSUE THREAD

**Issue by kashyapshiv** [trinsic-id/sdk-examples#165]
- I am using react wallet sample as a reference to integrate functionalities in my web-app, but the sample app is not working and I can't map the workings.
- The error I am getting in console, 
![image](https://user-images.githubusercontent.com/105337972/188880913-d4372a64-7d4b-41ef-b1da-bd16d4e68ee6.png)

@janpieterz

**Comment by janpieterz** [comment]
Hi @kashyapshiv , apologies for that. It should be fixed now in the main branch, the `searchWallet` function is the way to go.
