### ISSUE TITLE
Update the React Wallet Demo to sdk v1.6.0-rc2

### ISSUE THREAD

**Issue by fundthmcalculus** [trinsic-id/sdk-examples#47]
- [x] BLOCKER: 1.5 needs to be released for Node to continue

**Comment by MichaelEdwardBlack** [comment]
Changed this to 1.5 as 1.4 had that issue with the browser not supporting base64-url encoding

**Comment by fundthmcalculus** [comment]
@MichaelEdwardBlack this is done with PR: https://github.com/trinsic-id/sdk-examples/commit/99ab58501515bb128d285ec0599a9691ef88bd58
